### ISSUE TITLE
是否可以分享一下云盘视频, 谢

### ISSUE THREAD

**Issue by JerryCjr** [szy0syz/react-antd#2]

**Comment by szy0syz** [comment]
我买的是个人翻录的，ev4加密的 😂

**Comment by JerryCjr** [comment]
> 我买的是个人翻录的，ev4加密的 😂

haha 好吧 想白嫖一波来着

**Comment by JerryCjr** [comment]
> 我买的是个人翻录的，ev4加密的 😂

ev4 加密的这个有办法分享吗

**Comment by szy0syz** [comment]
加密还和服务器交互，难吧。

**Comment by JerryCjr** [comment]
了解 感谢


| |
jerryc_js
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年05月19日 18:22，Jerry Shi ***@***.***> 写道：

加密还和服务器交互，难吧。
